"all":
  "children":
    "databases":
      "hosts":
        "devops-app-db-staging": {}
    "webservers":
      "hosts":
        "devops-app-staging-0":
          "public_port": 8080
          "public_url": "http://localhost:8080"
        "devops-app-staging-1":
          "public_port": 8081
          "public_url": "http://localhost:8081"
        "devops-app-staging-2":
          "public_port": 8082
          "public_url": "http://localhost:8082"
  "vars":
    "ansible_connection": "docker"
    "ansible_python_interpreter": "/usr/bin/python3"
    "app_environment": "staging"
    "app_log_level": "debug"
    "app_name": "devops-app"
    "database_host": "devops-app-db-staging"
    "database_port": 5432
